# Generated by Django 4.2.5 on 2023-10-12 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Usuario', '0002_remove_usuario_edad_usuario_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('data_principal', models.BooleanField()),
                ('directorio', models.BooleanField()),
                ('apalancamiento', models.BooleanField()),
                ('accionistas', models.BooleanField()),
                ('impuesto', models.BooleanField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Usuario.usuario')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['id'],
            },
        ),
    ]
