# Generated by Django 4.2.5 on 2023-10-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0008_ciiu_nivel2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciiu_nivel2',
            name='ciiu',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
