# Generated by Django 4.2.5 on 2023-10-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0010_ciiu_operacinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciiu_operacinal',
            name='ciiu_operacional',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
