# Generated by Django 4.2.5 on 2023-10-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0011_alter_ciiu_operacinal_ciiu_operacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciiu_nivel2',
            name='ciiu',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ciiu_nivel2',
            name='descripcion',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
