# Generated by Django 4.2.5 on 2023-11-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0014_pais_provincia_cuidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nombre'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='ciiu_nivel2',
            options={'ordering': ['ciiu'], 'verbose_name': 'Ciiu Nivel 2', 'verbose_name_plural': "Ciiu's Nivel 2"},
        ),
        migrations.AlterModelOptions(
            name='ciiu_operacinal',
            options={'ordering': ['ciiu_operacional'], 'verbose_name': 'Ciiu Operacional', 'verbose_name_plural': "Ciiu's Operacionales"},
        ),
        migrations.AlterModelOptions(
            name='cuidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Cuidad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nombre'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['nombre'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.CreateModel(
            name='Entidad_Bancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_identificacin', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('no_inscripcion', models.CharField(blank=True, max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(null=True)),
                ('estado_permiso', models.CharField(blank=True, choices=[('Vigente', 'Vigente'), ('No Vigente', 'No Vigente')], default='Vigente', max_length=20, null=True)),
                ('sector', models.CharField(blank=True, choices=[('Privado', 'Privado'), ('Publico', 'Publico')], default='Privado', max_length=20, null=True)),
                ('sistema', models.CharField(blank=True, choices=[('Financiero', 'Financiero'), ('No Financiero', 'No Financiero')], default='Financiero', max_length=20, null=True)),
                ('capital_suscrito', models.FloatField(blank=True)),
                ('capital_autorizado', models.FloatField(blank=True)),
                ('valor_nominal', models.FloatField(blank=True)),
                ('ciiu_operacional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Principal.ciiu_operacinal')),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Principal.cuidad')),
            ],
            options={
                'verbose_name': 'Endidad Bancaria',
                'verbose_name_plural': 'Endidades Bancarias',
                'ordering': ['nombre'],
            },
        ),
    ]
