# Generated by Django 4.2.5 on 2023-11-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0016_entidad_bancaria_objeto_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidad_bancaria',
            old_name='estado_permiso',
            new_name='estado',
        ),
    ]
