# Generated by Django 4.2.5 on 2023-11-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0017_rename_estado_permiso_entidad_bancaria_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad_bancaria',
            name='fecha_inscripcion',
            field=models.DateField(null=True),
        ),
    ]
