# Generated by Django 4.2.5 on 2023-11-10 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0018_alter_entidad_bancaria_fecha_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=10)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=20, null=True)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas_cargo', to='App_Principal.cargo')),
                ('id_cargo_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas_cargo_2', to='App_Principal.cargo')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Principal.pais')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['nombres'],
            },
        ),
    ]
