# Generated by Django 4.1.13 on 2023-11-15 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0019_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad_bancaria',
            name='estado',
            field=models.CharField(blank=True, choices=[('Vigente', 'Vigente'), ('No Vigente', 'No Vigente')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entidad_bancaria',
            name='sector',
            field=models.CharField(blank=True, choices=[('Privado', 'Privado'), ('Publico', 'Publico')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entidad_bancaria',
            name='sistema',
            field=models.CharField(blank=True, choices=[('Financiero', 'Financiero'), ('No Financiero', 'No Financiero')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Apalancamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.FloatField(blank=True)),
                ('patrimonio', models.FloatField(blank=True)),
                ('apalancamiento', models.FloatField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Principal.entidad_bancaria')),
            ],
            options={
                'verbose_name': 'Apalancamiento',
                'verbose_name_plural': 'Apalancamientos',
                'ordering': ['entidad'],
            },
        ),
    ]
