# Generated by Django 4.1.13 on 2023-11-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0020_alter_entidad_bancaria_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apalancamiento',
            name='activo',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='apalancamiento',
            name='apalancamiento',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='apalancamiento',
            name='patrimonio',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
