# Generated by Django 4.1.13 on 2023-11-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0024_consejo_directivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consejo_directivo',
            old_name='fecha_inscripcion',
            new_name='fecha_asignacion',
        ),
    ]
