# Generated by Django 4.1.13 on 2023-11-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0025_rename_fecha_inscripcion_consejo_directivo_fecha_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor_interno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_endidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Principal.entidad_bancaria')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Principal.persona')),
            ],
            options={
                'verbose_name': 'Auditor Interno',
                'verbose_name_plural': 'Auditores Internos',
                'ordering': ['id_persona'],
            },
        ),
        migrations.CreateModel(
            name='Auditor_externo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrefirma', models.CharField(max_length=20, null=True)),
                ('id_endidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Principal.entidad_bancaria')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Principal.persona')),
            ],
            options={
                'verbose_name': 'Auditor Externo',
                'verbose_name_plural': 'Auditores Externos',
                'ordering': ['id_persona'],
            },
        ),
    ]
