# Generated by Django 4.1.13 on 2023-11-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0027_auditor_interno_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor_externo',
            name='empresa',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
