# Generated by Django 4.1.13 on 2023-11-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0028_auditor_externo_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditor_externo',
            options={'ordering': ['nombrefirma'], 'verbose_name': 'Auditor Externo', 'verbose_name_plural': 'Auditores Externos'},
        ),
        migrations.RemoveField(
            model_name='auditor_externo',
            name='id_persona',
        ),
    ]
