# Generated by Django 4.1.13 on 2023-11-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Principal', '0029_alter_auditor_externo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='excel',
            field=models.BooleanField(default=False),
        ),
    ]
