# Generated by Django 4.2.5 on 2023-10-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
